[package]
name = "rsalen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
anyhow = "1.0.42"
fs_extra = "1.2.0"
glob = "0.3.0"